config/routes.rb
Offline::Application.routes.draw do
  resources :data

    root :to => 'data#new'

end

app/models/datum.rb
class Datum < ActiveRecord::Base
 OPTION1 = ["Yes","No"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  # GET /data
  # GET /data.json
  def index
    @data = Datum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @data }
    end
  end

  # GET /data/1
  # GET /data/1.json
  def show
    @datum = Datum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @datum }
    end
  end

  # GET /data/new
  # GET /data/new.json
  def new
    @datum = Datum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @datum }
    end
  end

  # GET /data/1/edit
  def edit
    @datum = Datum.find(params[:id])
  end

  # POST /data
  # POST /data.json
  def create
    @datum = Datum.new(params[:datum])

    respond_to do |format|
      if @datum.save
        format.html { redirect_to new_datum_path, :notice => 'Data was successfully created.' }
        format.json { render :json => @datum, :status => :created, :location => @datum }
      else
        format.html { render :action => "new" }
        format.json { render :json => @datum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /data/1
  # PUT /data/1.json
  def update
    @datum = Datum.find(params[:id])

    respond_to do |format|
      if @datum.update_attributes(params[:datum])
        format.html { redirect_to @datum, :notice => 'Datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @datum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum = Datum.find(params[:id])
    @datum.destroy

    respond_to do |format|
      format.html { redirect_to data_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_form.html.erb
<%= form_for @datum, :html => { :class => 'form-inline' } do |f| %>
  <fieldset>
    <div>
    <span class="badge badge-inverse">Name&nbsp;&nbsp;&nbsp;&nbsp;
      <%= f.text_field :name, :class => 'text_field', :placeholder => "Enter Name..." %>
    </span>
    </div>
    <br />
    <div>
    <span class="badge badge-inverse">Age&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= f.number_field :age, :class => 'number_field', :placeholder => "Enter Age..." %>
    </span>
    </div>
    <br />
    <div>
    <span class="badge badge-inverse">Country
      <%= f.text_field :country, :class => 'text_field', :placeholder => "Enter Country..." %>
    </span>
    </div>
    <br />
    <div>
    <span class="badge badge-inverse">Gender </span>
    &nbsp&nbsp&nbsp
      Male&nbsp<%= f.radio_button("gender", "male") %>&nbsp&nbsp
      Female&nbsp<%= f.radio_button("gender", "female") %>
   
    </div>
    <br />
    <div>
    <span class="badge badge-inverse">Are you a graduate ?
    </span><br />
      <%= f.select(:q1, Datum::OPTION1)  %>
    </div>
    <br />
    <div>
    <span class="badge badge-inverse">What do you prefer recieving emails from us ?
    </span><br />
     I prefer to receive emails <%= f.check_box :q2 %>
    </div>
    <br /><br />
    <div class="form-actions">
      <%= f.submit'Create/Update', :class => 'btn btn-primary submit' %>
    </div>
  </fieldset>
<% end %>
<script>
$(function(){
});
  </script>

app/views/data/edit.html.erb
<%= render :partial => 'form' %>

app/views/data/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Country</th>
      <th>Gender</th>
      <th>Graduate</th>
      <th>Recieve Emails</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @data.each do |datum| %>
      <tr>
	<td><%= datum.name %></td>
	<td><%= datum.age %></td>
	<td><%= datum.country %></td>
  <td><%= datum.gender %></td>
  <td><%= datum.q1 %></td>
  <td>
    <% if(datum.q2.to_i == 1) %>
      Yes
    <% else %>
      No
    <% end %>
  </td>
	<td>
	  <%= link_to 'Destroy', datum_path(datum), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
	</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_datum_path, :class => 'btn btn-success' %>

app/views/data/new.html.erb
<%= render :partial => 'form' %>

app/views/data/show.html.erb
<h1>/Datum</h1>

<p>
  <b>Name</b><br>
  <%= @datum.name %>
</p>

<p>
  <b>Age</b><br>
  <%= @datum.age %>
</p>

<p>
  <b>Country</b><br>
  <%= @datum.country %>
</p>
<p>
  <b>Gender</b><br>
  <%= @datum.gender %>
</p>

<p>
  <b>Age</b><br>
  <%= @datum.q1 %>
</p>

<p>
  <b>Country</b><br>
  <%= @datum.q2 %>
</p>

<div class="form-actions">
  <%= link_to 'Back', data_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_datum_path(@datum), :class => 'btn' %>
  <%= link_to 'Delete', datum_path(@datum), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Offline</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>
    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
	<div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Local-Storage POC</a>
          <div class="container nav-collapse">
            <ul class="nav">
	      <li><%= link_to "All Records", data_path  %></li>
	      <li><%= link_to "New Record", new_datum_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
	  <div class="span8">
	    <%= yield %>
	  </div>
	  <div class="span2"></div>
	  <div class="span3 well">
	    <p>Locally stored items: <span id="local-count">0</span></p>
	    <p>You are working: <span id="status" class="offline">Offline</span></p>
	  </div>
	</div><!--/span-->
      </div><!--/row-->
    </div><!--/content-->

  <footer>
    <p>&copy; FIRM 2012</p>
  </footer>

</div> <!-- /container -->

<!-- Le javascript
================================================== -->

</body>
</html>